title: "Xinyu Su (Suzy)"
description: "PhD candidate at The University of Melbourne"
baseurl: ""
theme: jekyll-theme-minimal
logo: /assets/profile.jpg

# --- Add this section ---
show_downloads: false
github_username: suzy0223
email: suxs3@student.unimelb.edu.au
google_scholar: "https://scholar.google.com/citations?user=s6LkTiwAAAAJ&hl=en"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
