title: "Xinyu Su (Suzy)"
description: "PhD candidate at The University of Melbourne"
url: "https://suzy0223.github.io"
baseurl: ""
theme: jekyll-theme-minimal
logo: /assets/profile.jpg

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Socials
google_scholar: "https://scholar.google.com.au_
