title: Xinyu Su (Suzy)
description: "PhD candidate at The University of Melbourne"
url: "https://github.com/suzy0223"
baseurl: ""
theme: jekyll-theme-minimal
logo: /assets/profile.jpg
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Socials (edit as needed)
google_scholar: "https://scholar.google.com.au/citations?user=s6LkTiwAAAAJ&hl=en"
email: "suxs3@student.unimelb.edu.au"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
